import Head from 'next/head'
import { Inter } from 'next/font/google'
import { HeaderSideDiv , HomePageTitles , HomePageImage } from '@/components'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div
    className='p-0 overflow-hidden'
    >
      <Head>
        <title>Fitness AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSideDiv />
      <HomePageTitles />
      <HomePageImage />
    </div>
  )
}
